### ISSUE TITLE
Guide - Cloud.gov

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/cto-website#102]
For now, just link to the Cloud.gov and Cloud Foundry docs. This is less of a guide, more of a pointer to get developers to the right place to get started deploying on Cloud.gov.

**Comment by afeld** [comment]
Also relevant: https://pages.18f.gov/before-you-ship/infrastructure/

**Comment by jcastle** [comment]
Navin has been asking how to get started with sandboxes for Dev.  And I know very little about this, so the more simple the better.  😉

**Comment by jfredrickson5** [comment]
Finished the basic cloud.gov guide. Basically just links to the cloud.gov and Cloud Foundry docs, with a bit of info on org and space names to get developers started.

**Comment by jfredrickson5** [comment]
@jcastle let me know if the cloud.gov docs are straightforward enough to get started. Particularly the Usage -> Getting Started section.

**Comment by jcastle** [comment]
Yes, I am the ultimate test for providing easy to follow instructions.

Joseph Castle
GSA Digital Service
GSA IT, Office of the CTO
joseph.castle@gsa.gov
571-259-5843



On Sep 30, 2016, at 6:19 PM, Jeff Fredrickson <notifications@github.com>
wrote:

@jcastle <https://github.com/jcastle> let me know if the cloud.gov docs are
straightforward enough to get started. Particularly the Usage -> Getting
Started section.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GSA/cto-website/issues/102#issuecomment-250865646>, or mute
the thread
