### ISSUE TITLE
Pages subfolder

### ISSUE THREAD

**Issue by rdgsa** [GSA/cto-website#139]
Any reason this site isn't using a pages subfolder like the open.gsa.gov-redesign? Probably the more we can make those similar the easier for maintenance.

**Comment by jcastle** [comment]
Yes, created Trello cards for templates and components to standardize base
framework.

Joseph Castle
GSA Digital Service
GSA IT, Office of the CTO
joseph.castle@gsa.gov
571-259-5843



On Nov 3, 2016, at 9:57 AM, Ryan Day <notifications@github.com> wrote:

Any reason this site isn't using a pages subfolder like the
open.gsa.gov-redesign?
Probably the more we can make those similar the easier for maintenance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GSA/cto-website/issues/139>, or mute the thread

**Comment by jfredrickson5** [comment]
I've been meaning to clean up the root directory, including making that particular change.

**Comment by jfredrickson5** [comment]
Fixed in cff6a9952d0ffe944a6965260c4415bb2395318b
