### ISSUE TITLE
Update devsecops info

### ISSUE THREAD

**Issue by saracope** [GSA/cto-website#299]
I think this guide: https://tech.gsa.gov/guides/building_devsecops_culture/ needs updated to remove Jenkins (right?) and add in CircleCI.
Can you confirm that @jfredrickson5?

**Comment by jfredrickson5** [comment]
@saracope Yup, the table of approved tools should include CircleCI (and that table really should be a HTML table as opposed to an image).

The other diagrams are OK, though, since they're just examples. Projects can choose to use whatever approved CI they feel would be best, and I think Jenkins is still an option on our approved list. Though it should be made clear that Jenkins isn't the only option.

**Comment by saracope** [comment]
@jfredrickson5 Ok, I was thinking Jenkins had gotten pulled from the approved list for some reason.

**Comment by saracope** [comment]
@Bkim0928 Can you look at adding CircleCI to the list of GSA IT-Approved Tools under Build-Code, Test, Deploy.

**Comment by MaggieFero** [comment]
I'm going to stick this in and submit a PR since the issue's been dormant a while!
