### ISSUE TITLE
Move to federalist.18f.gov account

### ISSUE THREAD

**Issue by jcastle** [GSA/cto-website#5]
- [ ] Research best option - Sara has some ideas too
- [ ] Setup 18F Pages (Federalist) account - https://federalist.18f.gov - if option is chosen (concurrently working Cloud.gov account)

**Comment by jcastle** [comment]
Maybe start on federalist.18f.gov and move to Cloud.gov at a later date.  If deemed appropriate.

**Comment by konklone** [comment]
I believe the Federalist team is aware of this and will be reaching out. If they don't, the best contact there is @wslack.

**Comment by jcastle** [comment]
@jfredrickson5 work with @wslack to process the necessary paperwork.  @CinnyaSm and I can help with funding.

**Comment by jcastle** [comment]
@nvembar, changed cname file in gh pages to have a place holder for cto.gsa.gov.  We will continue to work the site through this repo with local view only through Jekyll serve.

**Comment by jfredrickson5** [comment]
Leaving this in the backlog until we can figure out which sprint it really fits in.

**Comment by jfredrickson5** [comment]
@jcastle @saracope @nvembar Take note, I'm making 'master' the new default branch for the cto-website repository. This is in preparation for our transition to Federalist (with the site continuing to be viewable on GitHub Pages as a secondary option). Please commit changes to 'master' rather than 'gh-pages'.

I am in the process of developing a script to build and deploy to gh-pages separately.
