### ISSUE TITLE
Remove API CISS email references

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/cto-website#912]
Remove reference to `API.CISS@gsa.gov` on open.gsa.gov. 

1) On the [About page](https://open.gsa.gov/contact/), under `How to get help with an API`, edit the text to the following:

You may also contact [GSA Office of the CTO][mailto:cto@gsa.gov] for assistance in identifying the best point of contact for an API.

2) On the [GitHub Adding API documentation](https://github.com/GSA/open-gsa-redesign/blob/master/APIDOCS.md) page please change the text to say:

The API documentation on open.gsa.gov is managed by the **CTO team**.

[Contact the **CTO team][mailto:cto@gsa.gov]** and ask for access to manage API docs, sharing your GitHub ID. Your GitHub ID will have to be in the GSA GitHub organization; follow the instructions in the [GitHub Administration repository](https://github.com/GSA/GitHub-Administration) if you haven't done so yet.

(there are like 5 other references to CISS on this page, please update all of them to be CTO with the correct email address!)

**Comment by jfredrickson** [comment]
Turns out I actually don't have access to the API Standards repo in order to implement #2 in this issue. Gray Brooks might have access, though, I'll ask him. Maybe we can split that item out into its own card?

As for updating the contact info on open.gsa.gov, the previews are ready here:
- [Contact Us page](https://federalist-ecc58765-2903-48b3-920c-5d93318ad084.sites.pages.cloud.gov/preview/gsa/open-gsa-redesign/jf/cto-contact/contact/)
- [APIDOCS markdown file](https://github.com/GSA/open-gsa-redesign/blob/236c3a4a713562a8db2c5f7c4112f0122ea22a7e/APIDOCS.md)

[PR link](https://github.com/GSA/open-gsa-redesign/pull/1213)

**Comment by vickimcfadden** [comment]
Thanks Jeff, looks good, I created a [new card for API standards](https://github.com/orgs/GSA/projects/114/views/1?pane=issue&itemId=62516745).
